version: "3.9"
services:

  aws:
    image: amazon/aws-cli:2.1.32
    env_file: .env
    volumes:
      - .:/work
      - ~/.aws:/root/.aws
    working_dir: /work

  envvars:
    image: flemay/envvars:0.0.7
    env_file: .env
    working_dir: /work
    volumes:
    - .:/work

  jq:
    image: imega/jq:1.6
    env_file: .env
    volumes:
      - .:/work
    working_dir: /work

  terraform:
    image: hashicorp/terraform:0.14.9
    env_file: .env
    entrypoint: ""
    volumes:
      - .:/work
      - ~/.aws:/root/.aws
    working_dir: /work